version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres
    ports:
      - '5432:${DATABASE_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
volumes:
  data: {}